name: FireML
channels:
  - conda-forge
  - defaults
dependencies:
  - boost-cpp=1.74.0=hf3dc895_5
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2021.10.8=h033912b_0
  - cairo=1.16.0=he01c77b_1009
  - certifi=2021.10.8=py38h50d1736_1
  - cffi=1.15.0=py38h1a44b6c_0
  - cfitsio=4.0.0=hb20e66c_0
  - curl=7.80.0=hf45b732_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - expat=2.4.1=he49afe7_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h10f422b_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h4cff582_1
  - freexl=1.0.6=h0d85af4_0
  - future=0.18.2=py38h50d1736_4
  - gdal=3.4.0=py38hf509309_2
  - geos=3.10.0=he49afe7_0
  - geotiff=1.7.0=h9e3163f_5
  - gettext=0.19.8.1=hd1a6beb_1008
  - giflib=5.2.1=hbcb3906_2
  - hdf4=4.2.15=hefd3b78_3
  - hdf5=1.12.1=nompi_h2f0ef1a_101
  - icu=69.1=he49afe7_0
  - importlib-metadata=4.8.2=py38h50d1736_0
  - importlib_metadata=4.8.2=hd8ed1ab_0
  - jbig=2.1=h0d85af4_2003
  - jpeg=9d=hbcb3906_0
  - json-c=0.15=hcb556a6_0
  - kealib=1.4.14=ha22a8b1_3
  - kiwisolver=1.3.2=py38h12bbefe_1
  - krb5=1.19.2=hcfbf3a7_3
  - lcms2=2.12=h577c468_0
  - lerc=3.0=he49afe7_0
  - libblas=3.9.0=12_osx64_mkl
  - libcblas=3.9.0=12_osx64_mkl
  - libcurl=7.80.0=hf45b732_0
  - libcxx=12.0.1=habf9029_0
  - libdap4=3.20.6=h3e144a0_2
  - libdeflate=1.8=h0d85af4_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.4.2=h0d85af4_5
  - libgdal=3.4.0=hc83da6b_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - libglib=2.70.0=hf1fb8c0_1
  - libiconv=1.16=haf1e3a3_0
  - libkml=1.3.0=h8fd9edb_1014
  - liblapack=3.9.0=12_osx64_mkl
  - libnetcdf=4.8.1=nompi_h6609ca0_101
  - libnghttp2=1.43.0=h6f36284_1
  - libpng=1.6.37=h7cec526_2
  - libpq=13.3=hea3049e_3
  - libprotobuf=3.18.1=hcf210ce_0
  - librttopo=1.1.0=heff5c8b_7
  - libspatialite=5.0.1=h4fc9923_11
  - libssh2=1.10.0=h52ee1ee_2
  - libtiff=4.3.0=hd146c10_2
  - libwebp-base=1.2.1=h0d85af4_0
  - libxml2=2.9.12=h7e28ab6_1
  - libzip=1.8.0=h8b0c345_1
  - libzlib=1.2.11=h9173be1_1013
  - llvm-openmp=12.0.1=hda6cdc1_1
  - lz4-c=1.9.3=he49afe7_1
  - matplotlib=3.4.3=py38h50d1736_2
  - matplotlib-base=3.4.3=py38hc7d2367_2
  - mkl=2021.4.0=h89fa619_689
  - ncurses=6.2=h2e338ed_4
  - ninja=1.10.2=h940c156_1
  - nspr=4.32=hcd9eead_1
  - nss=3.72=h31e2bf1_0
  - numpy=1.21.4=py38h49b9922_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1l=h0d85af4_0
  - pandas=1.3.4=py38ha53d530_1
  - pcre=8.45=he49afe7_0
  - pillow=8.4.0=py38hee640a0_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - poppler=21.10.0=h9573804_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=13.3=he8fe76e_3
  - proj=8.2.0=h1512c50_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyshp=2.1.3=pyh44b312d_0
  - python=3.8.12=h17280f6_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.0=cpu_py38h7f09a23_0
  - pytorch-cpu=1.10.0=cpu_py38he781eb1_0
  - pytz=2021.3=pyhd8ed1ab_0
  - readline=8.1=h05e3726_0
  - setuptools=58.5.3=py38h50d1736_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h6db0672_2
  - sqlite=3.36.0=h23a322b_2
  - tbb=2021.4.0=h940c156_1
  - tiledb=2.3.4=h8370e7a_0
  - tk=8.6.11=h5dbffcc_1
  - torchvision=0.10.1=py38h8b12d5a_0_cpu
  - tornado=6.1=py38h96a0964_2
  - typing_extensions=3.10.0.2=pyha770c72_0
  - tzcode=2021e=h0d85af4_0
  - tzdata=2021e=he74cb21_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xarray=0.20.1=pyhd8ed1ab_0
  - xerces-c=3.2.3=h6564042_4
  - xz=5.2.5=haf1e3a3_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h9173be1_1013
  - zstd=1.5.0=h582d3a0_0
prefix: /opt/anaconda3/envs/FireML
